### ISSUE TITLE
Enhance WebAuthnR

### ISSUE THREAD

**Issue by iwreilly** [webauthn4j/webauthn4j#1]

**Comment by iwreilly** [comment]
During validation, the attestationObject has been parsed and validated.  It would be useful if the parsed data, in particular the attestedCredentialData was made available to the caller.

One simple way of doing this would be to return the data from the validate method.

**Comment by ynojima** [comment]
Sorry for belated reply, and Thank you for your suggestion.
I'll address this issue with your proposed way. Thanks!

**Comment by ynojima** [comment]
This issue is addressed by 0f7e47d8d7e31091b7f2496e9d7064e83184fbef.
