### ISSUE TITLE
Improve the documentation for configuration options

### ISSUE THREAD

**Issue by hrstoyanov** [webauthn4j/webauthn4j#1031]
**Is your feature request related to a problem? Please describe.**

Currently WA4J does not explain two key activities before **registration** and **login**, leaving this for the developers to figure out:
- **PublicKeyCredentialCreationOptions** (registration)
- **PublicKeyCredentialRequestOptions** (login)

This **can be very frustrating** for those who have to develop passkeys workflows in both the client and the server! (I wasted days to figure out this). **This request is to provide some guidance on how to handle the "options" and save others time**.

**Describe the solution you'd like**
Some rational has been provided [here](https://github.com/webauthn4j/webauthn4j/discussions/692). This ask is to expand the documentation with:
 
- Explain why json deserialization in the browser is not enough, due to the use of Int8 byte arrays in the specification.
- Explain the options developers have in handling byte[] data: **base64** and **base64url**.
- Explain how to  to chose one (I think it is mentioned in paragraph 4.6, but it is not enough)
- Explain that by default, webauth4j uses **base64url**.
- Provide some sample code on the client(browser) and server side for creating options - example for registration initiation:

**Example for registration initiation**:

Server side (Java):
```java
//Configure the registration options.
var options = new PublicKeyCredentialCreationOptions(...);
//Configure a converter, specifically how to handle byte[]. By default it is base64url.
var OBJECT_CONVERTER =  new ObjectConverter();
var payload = OBJECT_CONVERTER.getJsonConverter().writeValueAsString(options);
response.send(payload);
```

Client(JavaScript):
```javascript
// Choose base64 or base64url decoder depending on the your server-side selection
//const base64Decoder = s => atob(s);
const base64urlDecoder = s => Uint8Array.from(atob(s.replace(/-/g, '+').replace(/_/g, '/')).split('').map(val => val.charCodeAt(0)));

// Fetch helper
const fetchWithErrorHandling = async (url, options) => {
   const response = await fetch(url, options);
   if (!response.ok) throw new Error(`Failed to fetch from ${url}: ${response.statusText}`);
   const data = await response.json();
   return data; 
};

// Fetch the registration options
const options = await fetchWithErrorHandling(`${baseUrl}/login/options`, { method: 'POST', body: formData });

// But you still need to handle byte[] !
const publicKey = {
      //you need to decode!
      challenge: base64urlDecoder(options.challenge),
      timeout: options.timeout,
      //you need to decode!
      allowCredentials: options.allowCredentials.map(({ credentialId, ...rest }) => ({...rest, id: base64urlDecoder(credentialId)}))
};

//Proceed with registration next.
const assertion = await navigator.credentials.get({ publicKey: publicKey});
```

**Example for login initiation**:

Server side (Java):
```java
//Configure the login options.
var options = new PublicKeyCredentialRequestOptions(...);
// See registration comments above
var payload = OBJECT_CONVERTER.getJsonConverter().writeValueAsString(options);
response.send(payload);
```

Client(JavaScript):
```javascript
const options = await fetchWithErrorHandling(`${baseUrl}/login/options`, { method: 'POST', body: formData });
//We still need to handle byte[] !
const publicKey = {
    challenge: base64urlDecoder(options.challenge),
    timeout: options.timeout,
    allowCredentials: options.allowCredentials.map(({ credentialId, ...rest }) => ({...rest, id: base64urlDecoder(credentialId)}))
};
// Proceed with login next.
const  assertion = await navigator.credentials.get({ publicKey: publicKey});
```

**Comment by ynojima** [comment]
I added some sample JavaScript code, but it utilizes [JSON serialization APIs for WebAuthn](https://developer.chrome.com/blog/passkeys-updates-chrome-129#json-serialization) instead of implementing its own base64url encoding code.

**Comment by ynojima** [comment]
You are right, I filed a new issue: https://github.com/webauthn4j/webauthn4j/issues/1047

**Comment by ynojima** [comment]
Oh, thank you for letting me know! I'll fix it.
