### ISSUE TITLE
The reference docs refer to AttestationStatementWrapper, which is now an inner static test class.

### ISSUE THREAD

**Issue by adrianfish** [webauthn4j/webauthn4j#1041]
**Describe the bug**
The reference documentation refers to a class named AttestationStatementEnvelope in the section on CredentialRecord serialization and deserialization. This class is actually in core/test and is a static inner class of AttestationStatementTest. I'm not sure how to serialize my attestation statement using this class, other than creating the wrapper class in my own code, which seems wrong.

**To Reproduce**
Look at the reference docs at https://webauthn4j.github.io/webauthn4j/en/#credentialrecord-serialization-and-deserialization. Look in the code at webauthn4j-core/src/test/java/com/webauthn4j/data/attestation/statement/AttestationStatementTest.java.

**Expected behavior**
A class called AttestationStatementEnvelope in the main section of code, not the test code.

**Comment by ynojima** [comment]
I'm sorry for causing confusion. I will update the document.
As `AttestationStatement` is not self-descriptive for its format, you need to create your own envelope class like `AttestationStatementEnvelope` in your code base. WebAuthn4J doesn't provide the class.
To store the format of the `AttestationStatement`, `attestationStatement` field of the envelope class must be anotated in this way, and the corresponding format property must return the format of the `AttestationStatement`.
```
class AttestationStatementEnvelope{

    @JsonProperty("attStmt")
    @JsonTypeInfo(
            use = JsonTypeInfo.Id.NAME,
            include = JsonTypeInfo.As.EXTERNAL_PROPERTY,
            property = "fmt"
    )
    private AttestationStatement attestationStatement;

    @JsonCreator
    public AttestationStatementEnvelope(@JsonProperty("attStmt") AttestationStatement attestationStatement) {
        this.attestationStatement = attestationStatement;
    }

    @JsonProperty("fmt")
    public String getFormat() {
        return attestationStatement.getFormat();
    }

    public AttestationStatement getAttestationStatement() {
        return attestationStatement;
    }
}
```

**Comment by adrianfish** [comment]
I did create my own envelope class in my code base, and it works as your describe. Thanks!
