### ISSUE TITLE
Module descriptor compiled with Java 17

### ISSUE THREAD

**Issue by vietj** [webauthn4j/webauthn4j#1042]
**Describe the bug**

Java 11 modular Maven project puts WebAuthn4J on the class path instead of module path

**To Reproduce**

Create a Maven modular Java 11 project with WebAuthn4J

**Expected behavior**

WebAuthn4J is put on the module path

**Additional context**

Module descriptors are Java 17 compiled which fails to load the module descriptor, instead it should be Java 11

**Comment by vietj** [comment]
Actually the entire jar targets java 17

```
Classfile jar:file:///Users/julien/.m2/repository/com/webauthn4j/webauthn4j-core/0.28.0.RELEASE/webauthn4j-core-0.28.0.RELEASE.jar!/com/webauthn4j/WebAuthnAuthenticationManager.class
  Last modified Nov 1, 2024; size 8242 bytes
  MD5 checksum 290b482ca24c21e328c1414580e77b76
  Compiled from "WebAuthnAuthenticationManager.java"
public class com.webauthn4j.WebAuthnAuthenticationManager
  minor version: 0
  major version: 61
```

**Comment by vietj** [comment]
thank you @ynojima let me know when there is a release

**Comment by ynojima** [comment]
Next release is scheduled to be Dec. 1st, but you can test the snapshot build with following cordinate in the snapshot repository: https://oss.sonatype.org/content/repositories/snapshots

```
        <dependency>
            <groupId>com.webauthn4j</groupId>
            <artifactId>webauthn4j-core-async</artifactId>
            <version>0.28.1-SNAPSHOT</version>
        </dependency>
```

Do you need a release now or can wait Dec. 1st release?

**Comment by ynojima** [comment]
`0.28.1.RELEASE` is just baked! :)
https://github.com/webauthn4j/webauthn4j/releases/tag/0.28.1.RELEASE

**Comment by ynojima** [comment]
@vietj  I sent a pull-request to vertx-auth: https://github.com/eclipse-vertx/vertx-auth/pull/700
