### ISSUE TITLE
Attestation validator does not detect expired leaf certificate 

### ISSUE THREAD

**Issue by valterlacamargo** [webauthn4j/webauthn4j#117]
**Framework:**
FIDO Conformance Tools v1.1.5(FIDO2 )

**Test:**
Server-ServerAuthenticatorAttestationResponse-Resp-5 Test server processing "packed" FULL attestation

**Request:**
F-6 Send ServerAuthenticatorAttestationResponse with FULL "packed" attestation, with attStmt.x5c contains a leaf certificate that is expired, and check that server returns an error 

**Response:**
Error: the string "Promise succeded when expected to fail!" was thrown, throw an Error :)
    at h.fail (js/vendor/mocha.min.js:1:43543)

**Comment by ynojima** [comment]
Thank you for filing the issue, but I couldn't reproduce it in my environment. 
Could you let me know your test environment ( WebAuthn4J version, Spring Security WebAuthn version(commit id), OS version, JDK version, etc.)

**Comment by ynojima** [comment]
The test is passed in my environment.
![image](https://user-images.githubusercontent.com/2139672/62953882-5164ae00-be29-11e9-8b28-9585aa49e240.png)
