### ISSUE TITLE
Attestation validator does not check leaf certificate dates

### ISSUE THREAD

**Issue by valterlacamargo** [webauthn4j/webauthn4j#118]
Framework:
FIDO Conformance Tools v1.1.5(FIDO2 )

Test:
Server-ServerAuthenticatorAttestationResponse-Resp-5 Test server processing "packed" FULL attestation

Request:
F-7 Send ServerAuthenticatorAttestationResponse with FULL "packed" attestation, with attStmt.x5c contains a leaf certificate that is not yet started, and check that server returns an error 

Response:
Error: the string "Promise succeded when expected to fail!" was thrown, throw an Error :)
at h.fail (js/vendor/mocha.min.js:1:43543)

**Comment by ynojima** [comment]
Thank you for filing the issue, but I couldn't reproduce it in my environment.
Could you let me know your test environment ( WebAuthn4J version, Spring Security WebAuthn version(commit id), OS version, JDK version, etc.)

**Comment by valterlacamargo** [comment]
Thank you for your attention. I have added you as a contributor in my project, so you can download and test whatever you want. 
WebAuthn4J version:  0.9.9-RELEASE
Spring Security WebAuthn version(commit id): Spring boot 2.1.6
OS version: Windows 10 pro Portuguese
JDK version:  adopt openjdk8u222b10 

Best Regards

**Comment by ynojima** [comment]
Wow, did you implemented FIDO server using WebAuthn4J? great work. 
Here is my own, which is based on spring-security: https://github.com/sharplab/spring-security-webauthn/tree/master/samples/javaconfig/webauthn/fido-server-conformance-test

I've filed an issue in your repository to point out the cause. I hope the issue and the my fido-server implementation will help.
