### ISSUE TITLE
Make enum types to have "fromJson" private static field

### ISSUE THREAD

**Issue by ynojima** [webauthn4j/webauthn4j#14]
Currently, enum types in WebAuthn4J have public static `create` factory method with `@JsonCreator` annotation.
Example:
https://github.com/webauthn4j/webauthn4j/blob/36d383ebebd61f97a72657a3667a12bfaa34ee65/webauthn4j-extras/src/main/java/com/webauthn4j/extras/fido/metadata/statement/AttestationType.java#L37-L55

The method is used from two way. One is "from Jackson deserializer", and the other is "from user code".
These usage is to better to be spitted into two methods: `create` and `fromJson`.

If `fromJson` is called with a wrong argument, it should throw `InvalidFormatException`, which is a Jackson exception. If `create` is called, it should throw `IllegalArgumentException`, which is a popular exception when the argument is wrong. 

Expected implementation:
- `create` method should be `public`, `static`, and NOT annotated with `@JsonCreator` method.
- `fromJson` method should be `private`, `static`, and annotated with `@JsonCreator` method.

`AttestationConveyancePreference` is a good example of expected implementation.
https://github.com/webauthn4j/webauthn4j/blob/5bf8b06a2569ef39c8cc1e3612735908f8fbc679/webauthn4j-core/src/main/java/com/webauthn4j/request/AttestationConveyancePreference.java#L34-L58

**Comment by ynojima** [comment]
These methods should be fixed too.
https://github.com/webauthn4j/webauthn4j/blob/d67241f2a3524d5731de8e8e137d86819708ab60/webauthn4j-core/src/main/java/com/webauthn4j/response/attestation/statement/COSEAlgorithmIdentifier.java#L43-L62
https://github.com/webauthn4j/webauthn4j/blob/36d383ebebd61f97a72657a3667a12bfaa34ee65/webauthn4j-core/src/main/java/com/webauthn4j/response/attestation/statement/COSEKeyOperation.java#L42-L67
https://github.com/webauthn4j/webauthn4j/blob/36d383ebebd61f97a72657a3667a12bfaa34ee65/webauthn4j-core/src/main/java/com/webauthn4j/response/attestation/statement/COSEKeyType.java#L37-L52
https://github.com/webauthn4j/webauthn4j/blob/3e4b26826d34c34949b6eb0bc43ad35f6a6df18a/webauthn4j-core/src/main/java/com/webauthn4j/response/attestation/statement/TPMEccCurve.java#L46-L68
https://github.com/webauthn4j/webauthn4j/blob/78a3a6c15445495551a95e5ac85b507567fa34cd/webauthn4j-core/src/main/java/com/webauthn4j/response/attestation/statement/TPMGenerated.java#L37-L43
https://github.com/webauthn4j/webauthn4j/blob/eff9b42d476a74bcc1d70f8270fc5761fb723635/webauthn4j-core/src/main/java/com/webauthn4j/response/attestation/statement/TPMIAlgHash.java#L40-L56
https://github.com/webauthn4j/webauthn4j/blob/eb48a676754240cca222622b9161acb1b612fecf/webauthn4j-core/src/main/java/com/webauthn4j/response/attestation/statement/TPMIAlgPublic.java#L38-L52
https://github.com/webauthn4j/webauthn4j/blob/78a3a6c15445495551a95e5ac85b507567fa34cd/webauthn4j-core/src/main/java/com/webauthn4j/response/attestation/statement/TPMISTAttest.java#L42-L66

**Comment by ynojima** [comment]
https://github.com/webauthn4j/webauthn4j/blob/36d383ebebd61f97a72657a3667a12bfaa34ee65/webauthn4j-core/src/main/java/com/webauthn4j/response/client/ClientDataType.java#L34-L46
https://github.com/webauthn4j/webauthn4j/blob/e44338ac166fee47274c58b76a804563960f7e97/webauthn4j-core/src/main/java/com/webauthn4j/response/client/Origin.java#L75-L81
https://github.com/webauthn4j/webauthn4j/blob/36d383ebebd61f97a72657a3667a12bfaa34ee65/webauthn4j-core/src/main/java/com/webauthn4j/response/client/TokenBindingStatus.java#L35-L49
https://github.com/webauthn4j/webauthn4j/blob/10cc05f4be839ed7404cbc019ebe92e31c9eadb3/webauthn4j-core/src/main/java/com/webauthn4j/util/jws/JWAIdentifier.java#L41-L60
https://github.com/webauthn4j/webauthn4j/blob/7273e014987ad5e2a35e2b8aa78ddcc0c8264eaa/webauthn4j-metadata/src/main/java/com/webauthn4j/metadata/data/toc/AuthenticatorStatus.java#L50-L85

**Comment by tnorimat** [comment]
I'm now fixing these codes. I'd like to issue its pull request afterwards.

**Comment by ynojima** [comment]
Addressed by #35
