### ISSUE TITLE
Add a minimal authentication validator interface

### ISSUE THREAD

**Issue by kasecato** [webauthn4j/webauthn4j#141]
**Is your feature request related to a problem? Please describe.**

Hello,

I want to save the authenticator data only `COSEKey`, `Counter` and `CredentialId` in my DB. Is this a bad idea?

I read your [WebAuthnAuthenticationContextValidator.validate()](https://github.com/webauthn4j/webauthn4j/blob/0.9.12.RELEASE/webauthn4j-core/src/main/java/com/webauthn4j/validator/WebAuthnAuthenticationContextValidator.java#L95) and it seems to be able to authenticate only with `COSEKey` and `Counter`. 

**Describe the solution you'd like**

I want an interface that takes `COSEKey` and `Counter` as arguments instead of `Authenticator`. 

```java
public WebAuthnAuthenticationContextValidationResponse validate(
    WebAuthnAuthenticationContext authenticationContext, 
    COSEKey coseKey, 
    long counter) throws WebAuthnException {
```

I think you will need to change the signature counter to the return value of this method, and implementers will need to update it manually.

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by ynojima** [comment]
Hmm. 
I'd like to keep using `Authenticator` interface to return updated counter value.
Isn't it good enough for you to make some of `Authenticator` methods default methods?

**Comment by kasecato** [comment]
Sure, I can use a `Authenticator` methods 👍 
Thanks.
