### ISSUE TITLE
Update know issues

### ISSUE THREAD

**Issue by kasecato** [webauthn4j/webauthn4j#142]
**Is your feature request related to a problem? Please describe.**

Hello,

First, I thank you for the valuable documentation that can be read in Japanese.

As you may have noticed, I think it's time to update [Known Issues](https://github.com/webauthn4j/webauthn4j/blob/0.9.12.RELEASE/docs/src/reference/asciidoc/en/known-issues.adoc), given the impact of this doc.

**Describe the solution you'd like**

- [Safari 13 - Added support for FIDO2-compliant USB security keys with the Web Authentication standard in Safari on macOS](
https://developer.apple.com/documentation/safari_release_notes/safari_13_release_notes)
- [Chrome 76 - Web Authentication API: Resident Key](https://www.chromestatus.com/feature/4627499185078272)
- [Firefox 66 - Passwordless Web Authentication Support via Windows Hello](https://blog.mozilla.org/security/2019/03/19/passwordless-web-authentication-support-via-windows-hello/)

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by ynojima** [comment]
Thank you for pointing out. Yes, it need to be updated. will do.

**Comment by ynojima** [comment]
Fixed by #158
