### ISSUE TITLE
Support internal authenticator transport

### ISSUE THREAD

**Issue by kasecato** [webauthn4j/webauthn4j#146]
**Is your feature request related to a problem? Please describe.**

I want to `internal` class to [AuthenticatorTransport](https://github.com/webauthn4j/webauthn4j/blob/0.9.12.RELEASE/webauthn4j-core/src/main/java/com/webauthn4j/data/AuthenticatorTransport.java). 
I can make it like below codes, but I thought it would be better to define it because it's also in the [specification](https://www.w3.org/TR/webauthn-1/#transport).
```java
AuthenticatorTransport.create("internal")
```

**Describe the solution you'd like**

```java
/**
 * Indicates the respective authenticator is contacted using a client device-specific transport.
 * These authenticators are not removable from the client device.
 */
public static final AuthenticatorTransport INTERNAL = new AuthenticatorTransport("internal");
```

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by ynojima** [comment]
Good catch. Thank you for your review. I made a fix in https://github.com/webauthn4j/webauthn4j/pull/147
