### ISSUE TITLE
Authenticator persistance

### ISSUE THREAD

**Issue by mathieuancelin** [webauthn4j/webauthn4j#148]
Hi,

in the readme of webauthn4j, you wrote something like

```java
save(authenticator); // please persist authenticator in your manner
Authenticator authenticator = load(credentialId); // please load authenticator object persisted in the registration process in your manner
```
I'm fine with that, but I failed to find a way to serialize and deserialize `Authenticator` instances. I tried several ways, using Jackson, converters, etc, but while serialization works, deserialization does not work :/

All the following examples fails :

```scala
val bytes = new CborConverter().writeValueAsBytes(authenticator)
println(bytes)
val auth = new CborConverter().readValue(bytes, classOf[Authenticator])
println(auth)
```
or
```scala
val json = new JsonConverter().writeValueAsString(authenticator)
println(json)
val auth = new JsonConverter().readValue(json, classOf[Authenticator])
println(auth)
```
or 
```scala
val module = new com.webauthn4j.converter.jackson.WebAuthnJSONModule(new JsonConverter(), new CborConverter())
val mapper = new ObjectMapper().registerModules(module)
val json = mapper.writeValueAsString(authenticator)
println(json)
val auth =  mapper.readValue(json, classOf[Authenticator])
println(auth)
```

can you explain what i'm doing wrong ?

Thanks

**Comment by ynojima** [comment]
```
val auth = new CborConverter().readValue(bytes, classOf[Authenticator])
```
You cannot deserialize to `Authenticator` interface. Instread of it, you need to specify concrete class that implments `Authenticator` interface.
The concrete class itself is not provided by webauthn4j. You need to create by your own ( `AuthenticatorImpl` is not designed for cbor serialization for now).

Here is an example class, which implements `Authentcator` from spring-security-webauthn,
https://github.com/sharplab/spring-security-webauthn/blob/master/samples/javaconfig/webauthn/spa/src/main/java/net/sharplab/springframework/security/webauthn/sample/domain/entity/AuthenticatorEntity.java
but it may not work with latest webauthn4j because of design change.

I'll add an example later.

**Comment by mathieuancelin** [comment]
@ynojima Thanks for you quick answer. I can't wait for the example :)

**Comment by ynojima** [comment]
I added `AttestedCredentialData` jackson serializer/deserializer to ease `Authenticator` implementation serialization (https://github.com/webauthn4j/webauthn4j/pull/152). 
It was released in 0.9.13.RELEASE today. https://github.com/webauthn4j/webauthn4j/releases/tag/0.9.13.RELEASE

Now, you can serialize `Authenticator` implementation in this way:
https://github.com/webauthn4j/webauthn4j/blob/master/webauthn4j-core/src/test/java/com/webauthn4j/authenticator/AuthenticatorTest.java#L40-L54

**Comment by kasecato** [comment]
@ynojima Why don't you implement `AuthenticatorImpl` like `AuthenticatorTest`?

**Comment by ynojima** [comment]
@kasecato I don't want to enforce a serialized format by putting jackson annotation on the class, but it may be useful for most users to put annotation on the class.
Anyway, I'll add enhance documents regarding `Authenticator` serialization.

**Comment by kasecato** [comment]
@mathieuancelin What do you think?

**Comment by ynojima** [comment]
Closes as this thread is stall.

**Comment by sergeev1chvn** [comment]
@mathieuancelin @ynojima hi, friends. tell me pls, I'm going to store the object as base64 in the postgresql database with the varchar type, how to choose the maximum size?

**Comment by ynojima** [comment]
credentialId is less than 1024 bytes.
attestedCredentialData is normally less than 1024 bytes
attestationStatement has no size limit, but normally less than 16384 bytes.
client extensions JSON size has no size limit.
authenticator extensions also has no size limit.

**Comment by sergeev1chvn** [comment]
@ynojima thx

**Comment by rehanbashir2211** [comment]
Can any one please share helping link or some piece of code? None of above examples are working for me

**Comment by ynojima** [comment]
webauthn4j-spring-security app can be a sample code. It persists data with JPA.
https://github.com/webauthn4j/webauthn4j-spring-security/blob/master/samples/spa/src/main/java/com/webauthn4j/springframework/security/webauthn/sample/domain/entity/AuthenticatorEntity.java

It uses converters defined in this directory: https://github.com/webauthn4j/webauthn4j-spring-security/tree/master/samples/spa/src/main/java/com/webauthn4j/springframework/security/webauthn/sample/infrastructure/util/jpa/converter
