### ISSUE TITLE
1.Cannot pass access token to FIDO Metadata Service/2.Mapping Error

### ISSUE THREAD

**Issue by CorneliaLahnsteiner** [webauthn4j/webauthn4j#206]
Both bug entries concern the experimental **webauthn4j-metadata service (0.10.0.RELEASE).**

**1.Cannot pass the access token to FidoMdsMetadataItemsProvider**
As described in the MetadataService of the FIDO Alliance, when retrieving metadata or TOC you have to enhance the URL with your access token. Example (this does not use a valid token): https://mds2.fidoalliance.org/?token=6d6b44d78b09fed0c5559e34c71db291d0d322d4d4de0000.
Unfortunately, I could not find a nice way (except overwriting the HTTPClient in FidoMdsMetadataItemsProvider) to add my access token to the URL of any request to the MDS of FIDO Alliance. Is there any way to do so? 

**2. Mapping Error**
I overwrote the HTTPClient in FidoMdsMetadataItemsProvider in order to add my access token to every request to the MDS of FIDO2 Alliance. But now I have to face a mapping problem in  FidoMdsMetadataItemsProvider#fetchMetadataStatement(), line 236:
MetadataStatement metadataStatement = jsonConverter.readValue(metadataStatementStr, MetadataStatement.class); metadataStatementStr should represent the response of the MDS of FIDO Alliance, and the metadataStatementStr cannot be mapped to the Class MetadataStatement.

**Comment by ynojima** [comment]
1.

The metadata module is still experimental, and `FidoMdsMetadataItemsProvider` needs polishing.
For now, please use `FidoMdsMetadataItemsProvider#setFidoMetadataServiceEndpoint` to set the endpoint with a token.

2.

It seems FIDO Alliance has changed the metadata file url. It now needs a valid token in its url.
https://mds2.fidoalliance.org/help

> This URL will not longer work as is. You must now append this URL with your Access Token as shown below: (this does not use a valid token)
> https://mds2.fidoalliance.org/metadata/4e4e%234005/?token=6d6b44d78b09fed0c5559e34c71db291d0d322d4d4de0000

I'll redesign the `FidoMdsMetadataItemsProvider`.

**Comment by ynojima** [comment]
Fixed in #207
