### ISSUE TITLE
Migrate to JUnit5

### ISSUE THREAD

**Issue by ynojima** [webauthn4j/webauthn4j#22]
WebAuthn4J uses JUnit4 for now, but it is good time to migrate to JUnit5.
It seems there is some migration support around JUnit.

#### junit-vintage-engine
junit-vintage-engine provides backward compatibility.

#### IntelliJ Quick Fixes
IntelliJ Quick Fixes helps rewriting test code to modern JUnit5 based code style.
https://blog.jetbrains.com/idea/2017/11/intellij-idea-2017-3-junit-support/

**Comment by DavidAdamczyk** [comment]
Can i help you?
