### ISSUE TITLE
ResidentKeyRequirement(changes in WebAuthn spec April 29th)

### ISSUE THREAD

**Issue by surfinbird** [webauthn4j/webauthn4j#268]
The webauthn specification was updated in late April, and there seems like there has been some changes to the parts concerning resident keys.

https://w3c.github.io/webauthn/#enumdef-residentkeyrequirement

In short: there is added a data type to AuthenticatorSelecetionCriteria, called ResidentKeyRequirement.

Will this be implemented in newer versions of webauthn4j?

**Comment by ynojima** [comment]
Yes, will do.

**Comment by ynojima** [comment]
Fixed in #270
