### ISSUE TITLE
Authenticator for Keycloak

### ISSUE THREAD

**Issue by stianst** [webauthn4j/webauthn4j#29]
**Is your feature request related to a problem? Please describe.**
Provide a Keycloak Authenticator leveraging WebAuthn4j.

**Describe the solution you'd like**
As a first step to get WebAuthn support into Keycloak it would be great to have an extension created for Keycloak that leverages WebAuthn4j to allow using Security Keys in place of OTP for two factor authentication.

The [experimental extension](https://github.com/stianst/keycloak-experimental/tree/master/fido-u2f) for FIDO U2F can be used as an inspiration.

We have an open issue for this in the Keycloak project here https://issues.jboss.org/browse/KEYCLOAK-9360. If anyone is interested in working on such an extension please let us know.

**Comment by ynojima** [comment]
Thank you for feature request!
After the discussion over e-mail on December, Webauthn4J welcomed @tnorimat and @tmogi001 from Hitachi team as maintainers, who has been contributing Keycloak in FAPI area.
As Dr. Nakamura have written in [KEYCLOAK-9358](https://issues.jboss.org/browse/KEYCLOAK-7159?jql=text%20~%20%22WebAuthn%22), they have intent to polish and maintain WebAuthn4J, and want to develop Keycloak Authenticator leveraging WebAuthn4j.

Yes, we are ready to take this issue :D

**Comment by stianst** [comment]
Great, thanks. Looking forward to playing with it once it's ready :)

**Comment by ynojima** [comment]
Thanks to @tnorimat and Keycloak maintainers, initial WebAuthn support was shipped in Keycloak 8.0.0 release. https://www.keycloak.org/docs/8.0/release_notes/index.html#w3c-web-authentication-support
