### ISSUE TITLE
Convert AttestedCredentialData to/from primitive type

### ISSUE THREAD

**Issue by ockendenjo** [webauthn4j/webauthn4j#312]
## Description

I'm having issues converting `AttestedCredentialData` to and from a primitive format

The README says:

```java
save(authenticator); // please persist authenticator in your manner
```
I've made an implementation of the `Authenticator` class. The important things in it seem to be `AttestedCredentialData` and the counter. In order to store the credential in my database I need to get everything to be in a primitive format such as `String`, `long` or `byte[]`. 

## Steps to reproduce
1. Perform credential registration to get instance of `AttestedCredentialData`
2. Use `ObjectMapper` to convert `AttestedCredentialData` to `String`
3. Use `ObjectMapper` to convert `String` to `AttestedCredentialData`
4. A 'com.fasterxml.jackson.databind.exc.MismatchedInputException' exception is thrown

```java
AttestedCredentialData attestedCredentialData; //value from registration
ObjectMapper mapper = new ObjectMapper();
String s = mapper.writeValueAsString(attestedCredentialData);

AttestedCredentialData reconstructed = mapper.readValue(s, AttestedCredentialData.class);
```

Am I doing something incorrectly? or is there a bug? 
Any comments much appreciated

## Additional context

Version: webauthn4j-core-0.12.0.RELEASE.jar

### mapper.writeValueAsString output

```json
{"aaguid":{"value":"00000000-0000-0000-0000-000000000000","bytes":"AAAAAAAAAAAAAAAAAAAAAA=="},"credentialId":"fJf9MRfLv/rbOdwjCc65e7h5dE2cbbFl7v45i37D/LemqS6m8LzzbIsL9PypJ/xmMSwywoeY9rAx3rfwLVbd+WHgV2UUKEeTWfWxvL5Es4ywSDf0PPi4K1ZF04l5DDF8","cosekey":{"1":"2","2":null,"3":-7,"4":null,"-1":1,"-2":"KDSi1g3UEe2RBq0wYK+jfG/w4dT2zZ7IM+maQw+/UBo=","-3":"fD2MqaGOqpcqPJAz0Ue/qaf34FEbhRh69sFug4rUFUg=","-4":null,"5":null,"1":2}}
```

### Exception message

```text
Cannot construct instance of `com.webauthn4j.data.attestation.authenticator.AAGUID` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)
```

**Comment by ynojima** [comment]
Thank you for raising issue. There should be more documentation.
To serialize/deserialize `AttestedCredentialData`, `com.webauthn4j.converter.AttestedCredentialDataConverter` can be used. It converts `AttestedCredentialData` to byte array.

**Comment by ockendenjo** [comment]
:+1: Thanks for pointing me in the correct direction. Seems to be working now
