### ISSUE TITLE
"ArrayIndexOutOfBoundsException: 1" on X.509 name parsing

### ISSUE THREAD

**Issue by staranchenko** [webauthn4j/webauthn4j#358]
Attestation object example (eWBM Goldengate G310): `o2NmbXRmcGFja2VkZ2F0dFN0bXSjY2FsZyZjc2lnWEgwRgIhANO/lCv6b9TaBxpUdKJYlEAybxFE+wm3gsdalBtGWNvcAiEAqbOGAkKvRgOdQ/6i3tdfV7zwwvG0FycVSCRdAu0eV/1jeDVjgVkCuDCCArQwggJZoAMCAQICCQC8XjO4t4aUKDAKBggqhkjOPQQDAjCBrzELMAkGA1UEBhMCS1IxETAPBgNVBAgMCFNlb3VsLVNpMRMwEQYDVQQHDApHYW5nbmFtLUd1MRcwFQYDVQQKDA5lV0JNIENvLiwgTHRkLjEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRlc3RhdGlvbjEcMBoGA1UEAwwTZVdCTSBDQSBDZXJ0aWZpY2F0ZTEdMBsGCSqGSIb3DQEJARYOaW5mb0BlLXdibS5jb20wHhcNMTkwNTAzMDYyNjEzWhcNMjkwNDI5MDYyNjEzWjCBsTELMAkGA1UEBhMCS1IxETAPBgNVBAgMCFNlb3VsLVNpMRMwEQYDVQQHDApHYW5nbmFtLUd1MRcwFQYDVQQKDA5lV0JNIENvLiwgTHRkLjEiMCAGA1UECwwZQXV0aGVudGljYXRvciBBdHRlc3RhdGlvbjEfMB0GA1UEAwwWZVdCTSBGSURPMiBDZXJ0aWZpY2F0ZTEcMBoGCSqGSIb3DQEJARYNaW5mb0Bld2JtLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAVN5las9Uq/YE9bBDsGp8nmimt7IhLzb2eb/ki3vR3Os7C4Zjj/RXBTNEN59KtUuZjM9CAr2UyMKD1FwWGwPQCjWjBYMAkGA1UdEwQCMAAwHwYDVR0jBBgwFoAUtyf38YgL9toq3QbPfEjg4Re5FP4wHQYDVR0OBBYEFEQuqVonVjHARnNctCAI2nncYGJxMAsGA1UdDwQEAwIF4DAKBggqhkjOPQQDAgNJADBGAiEAoE2KQ3uGe+Fq26U59E4Ls0lDNiIzEYEcRfDUp4Z2wCICIQDebEl4fZGEe92N+kUlfI/DPpyVu2ijoUakz2fe1X4gsmhhdXRoRGF0YVi2SZYN5YgOjGh0NBcPZHZgW4/krrmihjLHmVzzuoMdl2PFAAAAopVEKy7xXk3vsnDvsQb6y04AJOJW/7wgdqz2FHU/Jd9d57ZZfGGzMFdwxjMDBkVzRrHmAMAwMKUBAgMmIAEhWCDOdH7egzu6wQYBTxbfNL/SLhFiqgKOnHY64vBRfsTtJCJYIJmuBub2uZKG6Dj4n01JX77Yi23vgeSgYC4dvpViuezIoWtjcmVkUHJvdGVjdAI=`

DN: `EMAILADDRESS=info@ewbm.com, CN=eWBM FIDO2 Certificate, OU=Authenticator Attestation, O="eWBM Co., Ltd.", L=Gangnam-Gu, ST=Seoul-Si, C=KR`
RFC-2253 DN: `CN=eWBM FIDO2 Certificate,OU=Authenticator Attestation,O=eWBM Co.\, Ltd.,L=Gangnam-Gu,ST=Seoul-Si,C=KR`

Problem statement:
RFC-2253 DN is being splitted by comma and passed to `Attributes::new`. In this case ` Ltd.` is passed as a separate attribute ([source code](https://github.com/webauthn4j/webauthn4j/blob/master/webauthn4j-core/src/main/java/com/webauthn4j/data/x500/X500Name.java#L31)). Since it doesn't contain `=`, it can't be splitted to name and value, there is the only one element in the array out of two expected, thus `ArrayIndexOutOfBoundsException: 1` occurred ([source code](https://github.com/webauthn4j/webauthn4j/blob/master/webauthn4j-core/src/main/java/com/webauthn4j/data/x500/Attributes.java#L29)).

**Comment by ynojima** [comment]
Thank you for reporting this issue. I'll fix it.

**Comment by ynojima** [comment]
Fixed in #359
