### ISSUE TITLE
Lack of required "description" member in MetadataStatement.java

### ISSUE THREAD

**Issue by tnorimat** [webauthn4j/webauthn4j#40]
I've looked into FIDO Metadata Statement (Draft 27: at the time of this writing, this is the latest version of 2.0 Implementation Draft) and found that MetadataStatement.java did not contain required "description" member.

Please refer to the following link.
https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-metadata-statement-v2.0-id-20180227.html#widl-MetadataStatement-description

**Comment by tnorimat** [comment]
If this point is correct, I'd like to fix it.

**Comment by tnorimat** [comment]
One point I'd like to ask. Which version of specification should I look into ?

I've found the latest review draft as follows.
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-statement-v2.0-rd-20180702.html

**Comment by ynojima** [comment]
Good catch. Thank you for pointing out. It must be addressed. May I ask you to fix this?

**Comment by ynojima** [comment]
We need to catch up latest one until it is officially frozen (released).

**Comment by tnorimat** [comment]
Thank you for your advice.

BTW, should I only consider FIDO 2.0 Authenticator, and not consider FIDO UAF and U2F Authenticator?

**Comment by tnorimat** [comment]
And, I would like to fix this issue.

**Comment by ynojima** [comment]
> BTW, should I only consider FIDO 2.0 Authenticator, and not consider FIDO UAF and U2F Authenticator?

For metadata statement parsing, all authenticator family must be countered in.

**Comment by ynojima** [comment]
Fixed by https://github.com/Hitachi/webauthn4j/commit/7775a4ec4994219a71d3022c83c8d14daf216ba0
