### ISSUE TITLE
Verification method for VerificationMethodDescriptor.userVerification

### ISSUE THREAD

**Issue by tnorimat** [webauthn4j/webauthn4j#41]
FIDO Metadata Statement (Review Draft 02: at the time of this writing, this is the latest version of Review Draft) says userVerification member is a single USER_VERIFY constant and must be non-zero. 

I think we need some verification against this member.

Please refer to the following specification:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-statement-v2.0-rd-20180702.html#dictionary-verificationmethoddescriptor-members

**Comment by ynojima** [comment]
Thank you for suggestion. This seems to be addressed by fixing #42 (enum type introduction).

**Comment by ynojima** [comment]
Fixed by c05fa0571066cb8d51e87a99233ba2d869cc8254
