### ISSUE TITLE
emun of USER_VERIFY for User Verification Method

### ISSUE THREAD

**Issue by tnorimat** [webauthn4j/webauthn4j#42]
Related to #41, I think we need to prepare emun of USER_VERIFY like existing AttestationType.java.

Please refer to the following specification:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-registry-v2.0-rd-20180702.html#user-verification-methods

**Comment by ynojima** [comment]
Thank you for suggestion. This should be fixed as you proposed (introducing new enum type).

**Comment by ynojima** [comment]
Fixed by https://github.com/webauthn4j/webauthn4j/commit/326c72345431ff6c91284fd03538523e1f61b2ce
