### ISSUE TITLE
Verification method for MetadataStatement.protocolFamily

### ISSUE THREAD

**Issue by tnorimat** [webauthn4j/webauthn4j#43]
FIDO Metadata Statement (Review Draft 02: at the time of this writing, this is the latest version of Review Draft) says "uaf", "u2f", and "fido2" are supported as protocolFamily member's value.

I think we need some verification against this member.

Please refer to the following specification:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-statement-v2.0-rd-20180702.html#dictionary-metadatastatement-members

**Comment by ynojima** [comment]
What kind of validation do you have in mind? Checking whether it is in value range ( "uaf", "u2f", and "fido2")? It's nice to have.
