### ISSUE TITLE
Exception in AggregatingMetadataStatementsProvider when aggregating overlapping providers

### ISSUE THREAD

**Issue by Brinaviv** [webauthn4j/webauthn4j#435]
**Describe the bug**
When `AggregatingMetadataStatementsProvider` is aggregating two overlapping providers (I.e they have an AAGUID key in common), `provide()` fails with exception: 

> java.lang.IllegalStateException: Duplicate key 95442b2e-f15e-4def-b270-efb106facb4e (attempted merging values [com.webauthn4j.metadata.data.statement.MetadataStatement@31d7e70] and [com.webauthn4j.metadata.data.statement.MetadataStatement@67e37ba2])

At a glance, the same happens for `AggregatingMetadataItemsProvider`, but I haven't tested it.

**To Reproduce**
1. Create `JsonFileMetadataStatementsProvider p1`, such that `p1.provide()` yields a nonempty map.
2. Create a new `MetadataStatementsProvider` implementation p2, where:
`public Map<AAGUID, Set<MetadataStatement>> provide() { return p1.provide(); }`
3. Execute `new AggregatingMetadataStatementsProvider(new ArrayList(p1, p2)).provide()`

**Expected behavior**
For each `AAGUID` in any member of the `metadataItemsProviders`, the `AggregatingMetadataStatementsProvider` should `provide` a map, mapping `AAGUID` to the union of `Set[MetadataStatement]` mapped to `AAGUID` in each of the aggregated providers.

**Comment by ynojima** [comment]
This issue is still in TODO list. `wontfix` tag is removed.
