### ISSUE TITLE
Verification method for MetadataStatement.assertionScheme

### ISSUE THREAD

**Issue by tnorimat** [webauthn4j/webauthn4j#44]
FIDO Metadata Statement (Review Draft 02: at the time of this writing, this is the latest version of Review Draft) says "U2FV1BIN", "FIDOV2", and enumerated strings defined in the FIDO UAF Registry of Predefined Values are supported as assertionScheme member's value.

I think we need some verification against this member.

Please refer to the following specification:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-statement-v2.0-rd-20180702.html#dictionary-metadatastatement-members

**Comment by tnorimat** [comment]
I'm not sure whether we consider "FIDOV2" is only a valid value.

Moreover, I could not find enumerated strings defined in the FIDO UAF Registry of Predefined Values.

**Comment by ynojima** [comment]
From the point of parsing a metadata statement, "FIDOV2", "U2FV1BIN" and "UAFV1TLV" are all valid.
For WebAuthn Level1, "FIDOV2" and "U2FV1BIN are valid, but "UAFV1TLV" is not as of today. If a metadata statement is "UAFV1TLV", it is to be filtered out from the trust anchor source.
