### ISSUE TITLE
UserVerificationMethid does not support new types introduced

### ISSUE THREAD

**Issue by narras-oss** [webauthn4j/webauthn4j#442]
New user verification methods are being introduced and the enum UserVerificationMethod is not forward looking
Failing to de-serialize data for AAGUID = "34f5766d-1536-4a24-9033-0e294e510fb0" from FIDO MDS  as a result.

See spec https://fidoalliance.org/specs/common-specs/fido-registry-v2.1-ps-20191217.pdf
Additional values were added,

USER_VERIFY_PASSCODE_EXTERNAL 0x00000800 "passcode_external"
This flag MUST be set if the authenticator uses a local-only passcode (i.e. a passcode not known by the server) for
user verification that might be gathered outside the authenticator boundary.
USER_VERIFY_PATTERN_EXTERNAL 0x00001000 "pattern_external"
This flag MUST be set if the authenticator uses a drawn pattern

**Comment by ynojima** [comment]
Thank you for the report. I'll look into it.
