### ISSUE TITLE
HMAC Secret Extension (hmac-secret)

### ISSUE THREAD

**Issue by basharaj** [webauthn4j/webauthn4j#462]
**Is your feature request related to a problem? Please describe.**
Part of FIDO2 Interoperability Testing is HMAC extension test. See https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html#sctn-defined-extensions. I am curious if this feature is on the roadmap at all and if so if there is any ETA for it?

**Describe the solution you'd like**
Support for hmac-secret extension. 

**Describe alternatives you've considered**
sample implementation in C by Solo key: https://github.com/solokeys/solo/pull/149/files

**Comment by ynojima** [comment]
In my understanding, HMAC extension is part of FIDO2 CTAP specification, but not part of WebAuthn.
Could you explain the use-case you have in mind?
Does the FIDO2 conformance test suite require it for the server?

**Comment by basharaj** [comment]
@ynojima you're right. HMAC extension were requested as part of FIDO2 Interoperability Testing but I agree that it's not part of WebAuthn. I'll close this issue.
