### ISSUE TITLE
Verification method for MetadataStatement.authenticationAlgorithm(s)

### ISSUE THREAD

**Issue by tnorimat** [webauthn4j/webauthn4j#47]
FIDO Metadata Statement (Review Draft 02: at the time of this writing, this is the latest version of Review Draft) says authenticationAlgorithm is a single ALG_ (might be ALG_SIGN) constant defined in the FIDO Registry of Predefined Values and must be non-zero. authenticationAlgorithms has to be a list of such values.

I think we need some verification against this member.

Please refer to the following specification:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-statement-v2.0-rd-20180702.html#dictionary-metadatastatement-members

**Comment by tnorimat** [comment]
Its valid value depends on FIDO UAF or U2F or FIDO2 Authenticator.

**Comment by ynojima** [comment]
It seems checking whether the value is in the defined range or not is sufficient for this case. The check can be archived by an enum type introduction. 
Conditional validation that depends on protocol family is not requested by the spec.

**Comment by ynojima** [comment]
Fixed by c05fa0571066cb8d51e87a99233ba2d869cc8254
