### ISSUE TITLE
enum of ALG_SIGN for Authentication Algorithm

### ISSUE THREAD

**Issue by tnorimat** [webauthn4j/webauthn4j#48]
Related to #47, I think we need to prepare emun of ALG_SIGN like existing AttestationType.java.

Please refer to the following specification:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-registry-v2.0-rd-20180702.html#authentication-algorithms

**Comment by ynojima** [comment]
This is to be addressed. Thank you for pointing out.
Could you fix it?

**Comment by tnorimat** [comment]
Yes, I could.

**Comment by ynojima** [comment]
Fixed by #52
