### ISSUE TITLE
enum of ALG_KEY for Public Key Representation Format

### ISSUE THREAD

**Issue by tnorimat** [webauthn4j/webauthn4j#50]
Related to #49, I think we need to prepare emun of ALG_KEY like existing AttestationType.java.

Please refer to the following specification:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-registry-v2.0-rd-20180702.html#public-key-representation-formats

**Comment by ynojima** [comment]
This one need to be fixed too. Thanks!

**Comment by ynojima** [comment]
Fixed by #53
