### ISSUE TITLE
 about "conformance test"

### ISSUE THREAD

**Issue by choojunyup** [webauthn4j/webauthn4j#549]
hello.
I've looked through the entire list of issues and couldn't find any information, so I'm asking.
I made a fido server with webauthn4j lib.
And the fido conformance test(1.5.2v) is in progress.
Here are question.

1. How do you set up the "WebAuthnManager" for testing?
    Should I enable both  CertPathTrustworthinessValidator() and fidoMdsMetadataValidator() ?

<pre><code>
CustomWebAuthnConfig(){
 webAuthnManager = new WebAuthnManager(
	Arrays.asList(
		new PackedAttestationStatementValidator(),
	        new FIDOU2FAttestationStatementValidator(),
	        new TPMAttestationStatementValidator(),
	        new AndroidKeyAttestationStatementValidator(),
	        new AndroidSafetyNetAttestationStatementValidator(),
	        new AppleAnonymousAttestationStatementValidator(),
	        new NoneAttestationStatementValidator()
	),
	certPathTrustworthinessValidator(metadataStatementsProvider()),  //<-----
	new DefaultSelfAttestationTrustworthinessValidator()
	);
  webAuthnManager.getRegistrationDataValidator().getCustomRegistrationValidators().add(fidoMdsMetadataValidator());  <------
}
</code></pre>

  if you test with both enabled, "Metadata Service Tests" will not pass because of  "CertPathTrustworthinessValidator()".
  (It's probably not in the "metadata/test-tool" list.)
  

test spec&env
1. os : windows 10 pro
2. java : openjdk8
3. dev-tool : spring-boot 4.10v
4. fido-conformance-test-program version : 1.5.2v

**Comment by ynojima** [comment]
This is not an issue about webauthn4j, but a question. I'll convert this issue to a discussion entry and answer there.
