### ISSUE TITLE
enum of KEY_PROTECTION for Key Protection Type

### ISSUE THREAD

**Issue by tnorimat** [webauthn4j/webauthn4j#55]
I think we need to prepare emun of KEY_PROTECTION like existing AttestationType.java.

Please refer to the following specification:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-registry-v2.0-rd-20180702.html#key-protection-types

**Comment by tnorimat** [comment]
I'm afraid it seem not to be appropriate to treat KEY_PROTECTION itself as enum.

keyProtection member of MetadataStatement is a 16-bit number representing the bit fields:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-statement-v2.0-rd-20180702.html#widl-MetadataStatement-keyProtection

If treated same as like ALG_SIGN, ALG_KEY, ATTESTATION that are used as single value, we have to clarify valid bit field values  and treat them as enum.

**Comment by ynojima** [comment]
I think enum can be used for this case because not like C#'s enum, Java's enum cannot represent bit fields by itself, but combining with Set, it can be used for representing the bit fields (EnumSet seems popular in these cases, but I'd like to have immutable one).

**Comment by ynojima** [comment]
Fixed by https://github.com/webauthn4j/webauthn4j/commit/e9f4644105dfa434146d6efb2c21ba644c5a2821
