### ISSUE TITLE
Fix snyk's medium typed security issues

### ISSUE THREAD

**Issue by cseli** [webauthn4j/webauthn4j#553]
**Describe the bug**
After running the code analysis of [snyk](https://snyk.io/vuln) (report is not available online but can be run on demand), 4 medium typed issues were found. All of them are caused by `Arrays.equals()` method (`An attacker can guess the secret value of digest because it is compared using java.util.Arrays.equals, which is vulnerable to timing attacks. Use java.security.MessageDigest.isEqual to compare values securely.`)

**To Reproduce**
1. Go to [snyk](https://snyk.io/vuln/?type=maven)
2. Click on `Test your code`
3. Login with your github account
4. On the `Project` tab click on `Add project`, select `webauthn4j-device-check` 

**Expected behavior**
Output should be shown 4 Medium and 6 Low security issues
![Image Pasted at 2021-8-11 10-56](https://user-images.githubusercontent.com/8987031/129198566-390154aa-e056-4d84-9ef1-4bd359cbd79a.png)

**Comment by cseli** [comment]
Hey @ynojima, I would like to the use the `webauthn4j-device-check` module, but our security policy requires "clean" security report. I have already made a fix (as there were some tiny violations only), could you create a branch for me? Thanks you in advance!

**Comment by ynojima** [comment]
I couldn't see the "Medium" issue, but if you create a pull request from your forked repository, I'll review and merge it.
![image](https://user-images.githubusercontent.com/2139672/129207490-f7df84e9-be2a-40c6-9ac0-daf652e05982.png)

**Comment by cseli** [comment]
Forked and run the code analysis again and got the same result. 
<img width="1131" alt="Screen Shot 2021-08-12 at 16 03 50" src="https://user-images.githubusercontent.com/8987031/129210898-58e53d1d-f309-4ef3-8a3e-85338caa3be2.png">

As you recommended I created a [PR](https://github.com/cseli/webauthn4j/pull/1) from my repo, let me know if I miss something

**Comment by ynojima** [comment]
As I commented in your [pull-request](https://github.com/cseli/webauthn4j/pull/1), these issues are false positive. If there is a way to suppress the false positive snyk warnings, I will take it.

**Comment by cseli** [comment]
thank you for clarifying it, from out end there is no need to suppress those warning, feel free to close this issue

**Comment by ynojima** [comment]
Thank you for your reply. I'll close this issue.
