### ISSUE TITLE
General Exception handling

### ISSUE THREAD

**Issue by kvandermast** [webauthn4j/webauthn4j#57]
Hi,

We've been evaluating the project's source code a bit an saw that 
- (for example) AttestationStatementValidator does not include an exception signature in the "validate" method.
- The thrown examples are RuntimeExceptions (at least the ones extending from WebAuthnException).

Would it no be useful make a distinction between checked and unchecked exceptions? A failure in the validation of the signature should be catchable by the implementor of the library I would think?

Regards,
K

**Comment by ynojima** [comment]
Thank you for evaluation and feedback!

It is good idea to express exceptions in the signature of popular public methods. I'll work on it.
Also, I'll write documents about exceptions thrown by this library.

As checked exceptions don't fit well with lambda expression, I don't want to introduce checked exceptions.
