### ISSUE TITLE
AAGUIDSerializer / AAGUIDDeSerializer are missing in WebAuthnJSONModule

### ISSUE THREAD

**Issue by jpstotz** [webauthn4j/webauthn4j#655]
I assume this is a bug that AAGUIDSerializer / AAGUIDDeSerializer are registered in `com.webauthn4j.converter.jackson.WebAuthnCBORModule` but not in  `com.webauthn4j.converter.jackson.WebAuthnJSONModule`.

If you try to serialize/deserialize to/from JSON a class that contains an AAGUID field this will fail, as AAGUID class can not be deserialized without a proper deserializer or Jackson annotations 8which are not present). 

Edit: Upon closer inspection it seems that WebAuthnJSONModule misses a number of (de)serializers, that are registered for CBOR but not for JSON. In my opinion both modules should provide the same functionality so it would make sense to register all the serializer/deserializer instances in a common base class both modules are derived from.

**Comment by ynojima** [comment]
`com.webauthn4j.converter.jackson.serializer.cbor.AAGUIDSerializer` is intended to be used only for CBOR serialization.
W3C WebAuthn specification defines how to serialize AAGUID into CBOR, but not into JSON.
That's why WebAuthn4J doesn't provide AAGUID JSON serializer. WebAuthn4J leaves it to Applications (library user).
 Applications (library user) can register custom AAGUID JSON serializer or, use CBOR serializer instead.

**Comment by jpstotz** [comment]
@ynojima Even if something is not standardized by Webauthn I would assume that programmers would really appreciate it if there is a simple way to serialize/deserialize data like `AuthenticatorImpl`. I am really experienced with Jackson (de)serializing but it took me many hours and quite a few mixins to get it to work (at least for a minimal example without attestation).

Furthermore I had to bypass oddities like the CorseKey implementation which created defect JSON (duplicate field "1" - I assume this is the reason why Webauthn4j uses Jackson ObjectMapper with deactivated `FAIL_ON_UNKNOWN_PROPERTIES`). 

Summarizing I have to say that the data classes as they are implemented by Webauthn4j are designed in a way that makes (de)serialization very hard and complicated. If you only want to add features to the library that are covered by the Webauthn spec I would strongly recommend to extend the [WebAuthn4J Reference](https://webauthn4j.github.io/webauthn4j/en/) by adding some chapters that demonstrate how to easily save and load the major data classes of webauthn4j. 

In my opinion the best way would be to provide an `getEncoded()` method for the major data classes to get the class in serialized e.g. CBOR or whatever form (and a way to deserialize it). Application developers are not forced to use it but they could make use of it. Because of the wide variety of data formats that can appear it is otherwise extremely complicated to develop an own serialization format, especially considering that certain formats like AppleAnonymousAttestationStatement or AndroidSafetyNetAttestationStatement require certain hardware for generation of test cases.

**Comment by ynojima** [comment]
There is a documentation section about how to (de)serialize `Authenticator` members: https://webauthn4j.github.io/webauthn4j/en/#authenticator-serialization-and-deserialization
(We provide doc not about how to (de)serialize `Authenticator` itself, but about `Authenticator` members because the data is normally persisted in RDB and it is better to serialize per fields).

**Comment by ynojima** [comment]
Actually, JPA converters sample code that (de)serialize `Authenticator` members exists in webauthn4j-spring-security repository: 

`AuthenticatorEntity` implements the `Authenticator` interface, and JPA converters are provided to convert `Authenticator` members.
https://github.com/webauthn4j/webauthn4j-spring-security/blob/master/samples/spa/src/main/java/com/webauthn4j/springframework/security/webauthn/sample/domain/entity/AuthenticatorEntity.java
https://github.com/webauthn4j/webauthn4j-spring-security/tree/master/samples/spa/src/main/java/com/webauthn4j/springframework/security/webauthn/sample/infrastructure/util/jpa/converter

But there is no mention to the sample code in the documentation, I'll update the doc later, Thank you for pointing out.
