### ISSUE TITLE
JDK15 requirement to build WebAuthn4j

### ISSUE THREAD

**Issue by kvandermast** [webauthn4j/webauthn4j#683]
Hi, 

I just saw from the readme that the build now requires you to use JDK15 for EdDSA support. Why this choice for a hard (non LTS) dependency on JDK15?

As far as memory serves, JDK8 is still supported (2030), JDK11 till 2026. Why not combine these with a BouncyCastle and Google Tink dependency to include EdDSA support?

Thanks,
Kris

**Comment by ynojima** [comment]
Since JDK17 is LTS, I normally use it to build webauthn4j. You can keep using webauthn4j on JDK8 or JDK11 as long as you don't use EdDSA.
Since I want to keep dependencies minimal, I avoid using BouncyCastle or Google Tink.
