### ISSUE TITLE
AttestationOptionsEndpointFilter should be a Controller

### ISSUE THREAD

**Issue by blacelle** [webauthn4j/webauthn4j#700]
**Is your feature request related to a problem? Please describe.**
I'm considering relying on this library to implement WebAuthn in our project. However, we encounter some difficulties in its integration. One of them is wiring WebAuthn4J inside an existing application with a complex security layer (e.g. multiple existing WebSecurityConfigurerAdapter).

While we initially added an additional WebSecurityConfigurerAdapter dedicated to WebAuthn4J purposes, it does not work as simply as that as AttestationOptionsEndpointFilter has to receive a proper Authentication (from a not-WebAuthn4J filter) to return a proper userId.

com.webauthn4j.springframework.security.options.AttestationOptionsProviderImpl.DefaultPublicKeyCredentialUserEntityProvider.provide(Authentication)

    static class DefaultPublicKeyCredentialUserEntityProvider implements PublicKeyCredentialUserEntityProvider {

        @Override
        public PublicKeyCredentialUserEntity provide(Authentication authentication) {
            if(authentication == null){
                return null;
            }
            String username = authentication.getName();
            return new PublicKeyCredentialUserEntity(
                    username.getBytes(StandardCharsets.UTF_8),
                    username,
                    username
            );
        }
    }

Instead of making more complex our existing WebSecurityConfigurerAdapter, I would rather adding AttestationOptionsEndpointFilter logic as a Controller, through the existing securityFilterChains.

**Describe the solution you'd like**
Be provided a Controller (or anything not requiring to modify existing Filters) to respond similarly to AttestationOptionsEndpointFilter.

**Describe alternatives you've considered**
Writing this, I feel like I can code given Controller by myself. But it is cumbersome to rely on the same configuration as the one in my WebAuthn4JWebSecurityConfigurerAdapter given it relies on a WebAuthnLoginConfigurer (which is not @Bean friendly).

**Additional context**
-

**Comment by blacelle** [comment]
(As a side-note, we encountered issues as given Filter respond a AttestationOptions even if the HttpMethod is not GET (which is unexpected especially if the method is OPTIONS)).

**Comment by ynojima** [comment]
This seems an issue for `webauthn4j-spring-security`, not `webauthn4j`. Could you reopen at `webauthn4j-spring-security` project?

**Comment by blacelle** [comment]
I handled this through:

	// https://github.com/webauthn4j/webauthn4j/issues/700
	@Bean
	public AttestationOptionsProvider attestationOptionsProvider(ApplicationContext appContext,
			ObjectPostProcessor<Object> objectPostProcessor,
			AuthenticationManagerBuilder authenticationBuilder) throws Exception {
		Map<Class<?>, Object> sharedObjects = Collections.singletonMap(ApplicationContext.class, appContext);

		// We make a fake HttpSecurity to replay our configuration
		HttpSecurity http = new HttpSecurity(objectPostProcessor, authenticationBuilder, sharedObjects);

		// Replay our configuration
		configureWebAuthn4J(env, http);

		// Return a AttestationOptionsProvider as it would have been instantiated by WebAuthnLoginConfigurer
		return WebAuthn4hHacker.WebAuthnConfigurerUtil.newAttestationOptionsProvider(http);
	}

	@Bean
	public AttestationOptionsProviderController attestationOptionsProviderController(
			AuthenticationTrustResolver trustResolver,
			AttestationOptionsProvider attestationOptionsProvider) {
		return new AttestationOptionsProviderController(trustResolver, attestationOptionsProvider);
	}

Given class in webauthn4j packahe to access package-friendly methods:

```
package com.webauthn4j.springframework.security.config.configurers;

import org.springframework.security.config.annotation.web.HttpSecurityBuilder;

import com.webauthn4j.springframework.security.authenticator.WebAuthnAuthenticatorService;
import com.webauthn4j.springframework.security.challenge.ChallengeRepository;
import com.webauthn4j.springframework.security.options.AttestationOptionsProvider;
import com.webauthn4j.springframework.security.options.AttestationOptionsProviderImpl;
import com.webauthn4j.springframework.security.options.RpIdProvider;

public class WebAuthn4hHacker {

	public static final class WebAuthnConfigurerUtil {

		public static <H extends HttpSecurityBuilder<H>> RpIdProvider getRpIdProviderOrNull(H http) {
			return com.webauthn4j.springframework.security.config.configurers.WebAuthnConfigurerUtil
					.getRpIdProviderOrNull(http);
		}

		public static <
				H extends HttpSecurityBuilder<H>> WebAuthnAuthenticatorService getWebAuthnAuthenticatorServiceOrThrowException(
						H http) {
			return com.webauthn4j.springframework.security.config.configurers.WebAuthnConfigurerUtil
					.getWebAuthnAuthenticatorServiceOrThrowException(http);
		}

		public static <H extends HttpSecurityBuilder<H>> ChallengeRepository getChallengeRepositoryOrCreateNew(H http) {
			return com.webauthn4j.springframework.security.config.configurers.WebAuthnConfigurerUtil
					.getChallengeRepositoryOrCreateNew(http);
		}

		// Like
		// com.webauthn4j.springframework.security.config.configurers.WebAuthnConfigurerUtil.getAttestationOptionsProviderOrCreateNew(H)
		// But without trying from the ApplicationContext
		public static <
				H extends HttpSecurityBuilder<H>> AttestationOptionsProvider newAttestationOptionsProvider(H http) {
			return new AttestationOptionsProviderImpl(getRpIdProviderOrNull(http),
					getWebAuthnAuthenticatorServiceOrThrowException(http),
					getChallengeRepositoryOrCreateNew(http));
		}

	};

}

```
