### ISSUE TITLE
Windows Hello / Windows Hello For Business

### ISSUE THREAD

**Issue by Fabien38300** [webauthn4j/webauthn4j#702]
Hi,

Is there a way to differentiate Windows Hello and Windows Hello for Business authenticators ? 
It seems that both have the same aaguid

**Comment by ynojima** [comment]
I don't know the way to differentiate them.
As it is a library independent question, it is better to ask at [fido-dev group](https://groups.google.com/a/fidoalliance.org/g/fido-dev?pli=1). Someone may know the answer.
