### ISSUE TITLE
Issue parsing attestation for windows hello

### ISSUE THREAD

**Issue by sandeepdhankar-okta** [webauthn4j/webauthn4j#723]
hey @ynojima , we are using the library and facing some issues with parsing and wonder if you have any idea about it. It seem to be related with TPM and this exception specifically: com.webauthn4j.validator.exception.BadAttestationStatementException: The Subject Alternative Name extension of attestation certificate does not contain a TPM device property.

Underlying exception is Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to [B at com.webauthn4j.validator.attestation.statement.tpm.TPMAttestationStatementValidator.parseTPMDeviceProperty(TPMAttestationStatementValidator.java:323)

Failing AAGUID is 08987058-cadc-4b81-b6e1-30de50dcbe96.

The failure ties with parsing the following properties -
byte[] manufacturerAttr = (byte[])map.get("2.23.133.2.1");
byte[] partNumberAttr = (byte[])map.get("2.23.133.2.2");
byte[] firmwareVersionAttr = (byte[])map.get("2.23.133.2.3");

Thoughts/ Suggestions?

**Comment by ynojima** [comment]
Sorry for not responding. Will check and get back to you soon.

**Comment by sandeepdhankar-okta** [comment]
No worries, thanks for looking into this. I am trying on my end as well, reached out in case you already have some idea about this as this is going to be a common issue.

**Comment by sandeepdhankar-okta** [comment]
To add more color to it, windows has both hardware and software based platform authenticators and the problematic one is hardware based. Unfortunately the usage of hardware authenticator is much higher than software one.

**Comment by sandeepdhankar-okta** [comment]
Dumping more data here, seems like the cert that we get is something like this 
`[ [   Version: V3   Subject:    Signature Algorithm: SHA256withRSA, OID = 1.2.840.113549.1.1.11    Key:  Sun RSA public key, 2048 bits   modulus: 26957042200824286021375455843732414930936437920472683854216341694637335715194182762141035542017843717092538949534239672470776195534980082316500571857745625305439572610988222947509115837336127274872836149089717783211453733405068889940132591427824440107181599987507517056311988242237739359846820253988928113682143280095723833528373837291733504300881945101099011949198181599830016581130017908723609555237627736990067137420598461097442836000875787604493492174209001170357732209162741242380503616782659065750983432008880674885476216376754657121450450012683959349679036352629697031621855052468191300379982838811172801117813   public exponent: 65537   Validity: [From: Sun Jul 07 20:28:13 UTC 2019,                To: Fri Mar 21 20:29:09 UTC 2025]   Issuer: CN=EUS-NTC-KEYID-1591D4B6EAF98D0104864B6903A48DD0026077D3   SerialNumber: [    10c9ef9b f9374c94 b9890495 663d531a]  Certificate Extensions: 8 [1]: ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false AuthorityInfoAccess [   [    accessMethod: caIssuers    accessLocation: URIName: http://azcsprodeusaikpublish.blob.core.windows.net/eus-ntc-keyid-1591d4b6eaf98d0104864b6903a48dd0026077d3/56590fa8-3f40-434f-b35b-ed59ff547469.cer ] ]  [2]: ObjectId: 2.5.29.35 Criticality=false AuthorityKeyIdentifier [ KeyIdentifier [ 0000: 1D 06 2E EE 78 56 7C FD   A4 72 4F 2B B4 52 48 89  ....xV...rO+.RH. 0010: 56 D0 4B A7                                        V.K. ] ]  [3]: ObjectId: 2.5.29.19 Criticality=true BasicConstraints:[   CA:false   PathLen: undefined ]  [4]: ObjectId: 2.5.29.32 Criticality=true CertificatePolicies [   [CertificatePolicyId: [1.3.6.1.4.1.311.21.31] [PolicyQualifierInfo: [   qualifierID: 1.3.6.1.5.5.7.2.2   qualifier: 0000: 30 44 1E 42 00 54 00 43   00 50 00 41 00 20 00 20  0D.B.T.C.P.A. .  0010: 00 54 00 72 00 75 00 73   00 74 00 65 00 64 00 20  .T.r.u.s.t.e.d.  0020: 00 20 00 50 00 6C 00 61   00 74 00 66 00 6F 00 72  . .P.l.a.t.f.o.r 0030: 00 6D 00 20 00 20 00 49   00 64 00 65 00 6E 00 74  .m. . .I.d.e.n.t 0040: 00 69 00 74 00 79                                  .i.t.y  ]]  ] ]  [5]: ObjectId: 2.5.29.37 Criticality=false ExtendedKeyUsages [   2.23.133.8.3 ]  [6]: ObjectId: 2.5.29.15 Criticality=true KeyUsage [   DigitalSignature ]  [7]: ObjectId: 2.5.29.17 Criticality=true SubjectAlternativeName [   OID.2.23.133.2.3=id:13 + OID.2.23.133.2.2=NPCT6xx + OID.2.23.133.2.1=id:4E544300 ]  [8]: ObjectId: 2.5.29.14 Criticality=false SubjectKeyIdentifier [ KeyIdentifier [ 0000: 33 16 DB 1C 63 DE DB F2   E1 89 69 72 69 AB 54 15  3...c.....iri.T. 0010: E7 28 D8 98                                        .(.. ] ]  ]   Algorithm: [SHA256withRSA]   Signature: 0000: A9 F0 AD DA 85 60 F3 94   90 15 A5 D6 6F 61 D1 4C  .....`......oa.L 0010: 68 2D A7 FD 8B AB 2A 5B   6F 29 03 45 F0 7F 11 C8  h-....*[o).E.... 0020: 28 6D D1 11 C3 D6 BC D9   24 AD D8 C4 C4 E7 97 07  (m......$....... 0030: D2 50 1C 89 C7 2E 67 7E   70 4F 9C 04 A3 14 83 51  .P....g.pO.....Q 0040: C8 98 A4 2F A6 A3 E6 03   39 65 72 6E 1C 01 9E DD  .../....9ern.... 0050: 3E 3E 10 C7 13 CD 45 37   27 7A 3A CA 66 DB 5F 18  >>....E7'z:.f._. 0060: 21 2F 34 5F 4D 7C 40 FB   FC 94 49 44 09 6B E5 73  !/4_M.@...ID.k.s 0070: 94 23 A7 8E 81 58 6C F7   73 A2 EA E3 6D 39 B0 3E  .#...Xl.s...m9.> 0080: F9 A4 E9 0F 48 56 B6 DA   BA 3A 89 AC 27 F9 32 39  ....HV...:..'.29 0090: 67 DA B7 DD 25 36 41 3E   7C 07 60 1D 12 BC 52 3F  g...%6A>..`...R? 00A0: 15 D4 24 F3 7E FF BC 62   89 4C 16 79 A6 A3 C5 4F  ..$....b.L.y...O 00B0: FE 1F DB AA F5 5C AA 71   93 A6 05 0D 2B 9E 33 E0  .....\.q....+.3. 00C0: 0F 3A F3 76 A5 F0 BC 78   E5 A0 60 EE BA 3B B4 91  .:.v...x..`..;.. 00D0: 93 F1 E0 D8 59 F6 B2 27   58 90 22 01 17 F7 4E EC  ....Y..'X."...N. 00E0: FC DE 20 AA 2B 85 38 46   83 54 C0 1D EE 69 1E 7C  .. .+.8F.T...i.. 00F0: 1D 6F E3 95 7E 34 E8 27   0F BF B3 4F 46 06 A4 B1  .o...4.'...OF... 0100: 9A 3B AF 57 97 37 FE DA   DE 0D 09 64 D8 FA 99 0B  .;.W.7.....d.... 0110: 38 EA C9 77 D0 1C 08 9A   40 49 D1 E5 97 87 A8 6F  8..w....@I.....o 0120: 3E 33 36 EC 39 D9 94 AF   0F 7B 46 80 DB 8B 4B 56  >36.9.....F...KV 0130: 4E 5C D3 1F 39 E2 28 20   90 9D 9E 26 D3 7D 37 E2  N\..9.( ...&..7. 0140: A4 74 96 E9 E0 C4 84 89   C1 05 D2 44 35 5A E7 C3  .t.........D5Z.. 0150: 36 C0 3C 36 92 40 07 97   65 E9 3D B6 69 25 AE D0  6.<6.@..e.=.i%.. 0160: 90 2C 80 3F 8C CB CE E2   8D 67 FE 42 90 F1 A0 E4  .,.?.....g.B.... 0170: 4D FA 96 E1 80 D8 37 1F   76 B9 AD 28 9C 1A 2B 73  M.....7.v..(..+s 0180: 22 FE A6 0D 22 8A 6C 2D   6A 80 F8 5A FF 05 8B 10  "...".l-j..Z.... 0190: D9 68 36 55 BB DB 46 4F   1B 4D B7 C2 7E AC FC F1  .h6U..FO.M...... 01A0: BC 35 AD 20 9C 96 97 1B   C4 5B 2B EF BD 94 C6 0C  .5. .....[+..... 01B0: 35 08 C1 1C 21 C2 41 85   A7 ED 87 C3 95 91 B4 93  5...!.A......... 01C0: F6 89 F6 5F E6 6A F1 31   4C 45 15 6C 30 F6 A2 18  ..._.j.1LE.l0... 01D0: E4 83 A1 84 BC BA F5 D7   4B BA 0A D2 AC B7 51 41  ........K.....QA 01E0: E8 DD 02 FA A8 E2 B6 E8   7F 27 B9 F3 7C 39 6B 32  .........'...9k2 01F0: 46 A5 C2 EE 1D 09 A0 4E   AB AA A8 C3 62 80 0E F5  F......N....b...  ]` 

I tried to look at the test cases for TPM attestation and on high level it seems they are expecting data in different format `https://github.com/webauthn4j/webauthn4j/blob/d9f75a77dfc2bff71a7b1501dd98361a81d302ba/webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/TPMAuthenticator.java#L73`

**Comment by sandeepdhankar-okta** [comment]
I know its a library and the behavior is justified to throw exception, I still feel there is some room to log the errors and have soft failure on these things which allows the library user to make a call to continue or abort the operation.

**Comment by ynojima** [comment]
Is it possible to paste the attestation certificate in pem format or the `AuthenticatorData` byte array?

**Comment by sandeepdhankar-okta** [comment]
I am afraid I do not have data in that format. This is the best I could dig from some sources for the error.

**Comment by ynojima** [comment]
Umm, to reproduce the error, I need the attestation certificate data. 
Is it possible to take `attestationObject` byte array data in the `RegistrationRequest` object?
The `RegistrationRequest` is the container object to pass data to WebAuthn4J. 
https://github.com/webauthn4j/webauthn4j/blob/master/webauthn4j-core/src/main/java/com/webauthn4j/data/RegistrationRequest.java#L40

**Comment by sandeepdhankar-okta** [comment]
I understand the difficulty, curious how did you come up with the format for the test case, explicitly this one - https://github.com/webauthn4j/webauthn4j/blob/d9f75a77dfc2bff71a7b1501dd98361a81d302ba/webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/webauthn/TPMAuthenticator.java#L73

**Comment by ynojima** [comment]
I assume it was taken from my Windows Hello machine's dump.

**Comment by sandeepdhankar-okta** [comment]
To clarify, you mean you got this in the enrollment response for the windows machine and thats how you used it for the tests as well?

**Comment by sandeepdhankar-okta** [comment]
Also I looked at the code https://github.com/Yubico/java-webauthn-server/blob/19a51c50b36114b56bd9c0142ca5411e3371f561/webauthn-server-core/src/main/java/com/yubico/webauthn/TpmAttestationStatementVerifier.java#L488 on how they are handling the flow in such a situation. I did like the fact that there is a null check on the map item before doing anything else. I believe this is a fine line to log exception instead of throwing it.

**Comment by ynojima** [comment]
> To clarify, you mean you got this in the enrollment response for the windows machine and thats how you used it for the tests as well?

Yes, as far as  I recalled.

>  I did like the fact that there is a null check on the map item before doing anything else. I believe this is a fine line to log exception instead of throwing it.

Yes, null check is nice to have. WebAuth4J throws `BadAttestationStatementException`, but it will be more better if it contains a more specific error message based on null check.

**Comment by sandeepdhankar-okta** [comment]
Is it ok if I add a null check and return unknown/undetermined as the response instead of throwing the exception or you feel it has to be parsed correctly from security aspect?

**Comment by ynojima** [comment]
WebAuthn spec expects: 
> The Subject Alternative Name extension MUST be set as defined in [TPMv2-EK-Profile] section 3.2.9.
https://w3c.github.io/webauthn/#sctn-tpm-cert-requirements

[TPMv2-EK-Profile] section 3.2.9 expects:
This contains the alternative name of the entity associated with this certificate. The issuer MUST
include TPM manufacturer, TPM part number and TPM firmware version, using the directoryNameform within the GeneralName structure.
https://www.trustedcomputinggroup.org/wp-content/uploads/Credential_Profile_EK_V2.0_R14_published.pdf

I think exception must be thrown instead of accepting it.
Without regarding it as an error, as far as I remember, it doesn't pass FIDO conformance test.

**Comment by ynojima** [comment]
> Probably moving it to separate block and trying to parse with multiple known formats could be good solution that satisfies the requirement for now?

I agree with you. Extracting a parser interface, preparing some default implementations, and leaving room to create custom injectable implementations is the best option here. 
But to prepare a default implementation that can parse the certificate you faced, it is appreciated if you could give me the attestation certificate in pem format.

**Comment by rmmeans** [comment]
I think this issue can be closed. Do you agree @sandeepdhankar-okta?  We saw the same thing with Windows 11 on version 22H2, once we updated to the January release:`0.20.7.RELEASE`, the issue was resolved.

Found the source from MS that details the change: https://learn.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/webauthn-apis
