### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by WakaWakaMan** [webauthn4j/webauthn4j#734]
Hi, 

`NoSuchMethodError` occurs in method `getBytesFromECPublicKey()`.
https://github.com/webauthn4j/webauthn4j/blob/e0b1a78fe946076a856bb31298e23eff5cab72b1/webauthn4j-test/src/main/java/com/webauthn4j/test/authenticator/u2f/FIDOU2FAuthenticator.java#L126

Same issue as here:
https://github.com/webauthn4j/webauthn4j/pull/676/commits

**Comment by ynojima** [comment]
Thank you for pointing that out! Fixed in #738
