### ISSUE TITLE
RpIdHashValidator returns failure when used with AppID

### ISSUE THREAD

**Issue by trixpan** [webauthn4j/webauthn4j#771]
According to this:

> **Client extension output**
Returns the value of output. If true, the AppID was used and thus, when verifying the assertion, the Relying Party MUST expect the rpIdHash to be the hash of the AppID, not the RP ID.

This doesn't seem to be the case of 

https://github.com/webauthn4j/webauthn4j/blob/fb2d39bf3188115136c6f8d1ef9de8d08019b0a1/webauthn4j-core/src/main/java/com/webauthn4j/validator/RpIdHashValidator.java#L52

**Comment by trixpan** [comment]
@ynojima manufacturers still issie keys with U2F personalisation during mass issuance of tokens. Using it with things like keycloak (custom implementation of authenticator SPI)is really handy to ensure WebauthN FIDO2 registration happens after pre-authentication using AppID. 

And as you mentioned, there are also advantages of migrating users from U2F to WebauthN.

**Comment by trixpan** [comment]
> Could you elaborate this? Do you mean U2F key manufacturers accepts importing of U2F keypair encryption master key, and enterprise IdP operator can provision an user account with U2F key registered without using FIDO U2F browser API?

That is correct. Some manufacturers will provision U2F keypairs and ship them pre-provisioned to a particular AppID. You then can use Key Handle and Public Keybto validate the bootstrapping of WebauthN.

**Comment by trixpan** [comment]
@ynojima I know first hand some manufacturers will only provision U2F (can't share the dociments tho). Literally had to write and appid  authenticator in order to support onboarding of users into our IdP.  :-\

Should I raise a PR to pass appid to rpidhash validator when appid extension is true?

**Comment by ynojima** [comment]
> Literally had to write an appid authenticator in order to support onboarding of users into our IdP. :-\

Oh, that's a shame. I welcome your PR.
