### ISSUE TITLE
Different user interfaces on android chrome

### ISSUE THREAD

**Issue by billlyd123** [webauthn4j/webauthn4j#778]
### Discussed in https://github.com/webauthn4j/webauthn4j/discussions/777

<div type='discussions-op-text'>

<sup>Originally posted by **billlyd123** April 13, 2023</sup>
Hi I am noticing different UIs on android chrome between different websites. One of them is able to detect my Yubikey 5Ci and the other is not. Is there different ways of calling the API that generate different UIs?
<img width="416" alt="image" src="https://user-images.githubusercontent.com/30014142/231891676-461ee30e-e35b-422d-b982-28b6e30fc409.png">
![image](https://user-images.githubusercontent.com/30014142/231892072-b7643ae6-f64b-469c-94c7-4e8cc095f84e.jpg)
</div>

**Comment by blacklion9279** [comment]
I am seeing the same issue as well. can this be fixed soon?

**Comment by ynojima** [comment]
Sorry for late response.
It seems the one for `demo.yubico.com` is a UI for legacy WebAuthn(non-resident(non-discoverable) credential), and the other is an UI for passkey.
Since I'm not the owner of these sites, I don't know the details but maybe latter is using option that allows passkey.

**Comment by billlyd123** [comment]
I am the developer of this site, these are the options for key creation.
{
  "rp": {
    "id": "**",
    "name": "**"
  },
  "user": {
    "id": "**",
    "name": "admin",
    "displayName": "admin"
  },
  "challenge": "**",
  "pubKeyCredParams": [
    {
      "type": "public-key",
      "alg": -7
    },
    {
      "type": "public-key",
      "alg": -257
    }
  ],
  "timeout": 300000,
  "excludeCredentials": [
    {
      "type": "public-key",
      "id": "261K4PsjmbyOEyZN642zH6dhtkygrIDiWbQTVWfcQE0fcctqVpdCpQD0XueyPsi4"
    }
  ],
  "authenticatorSelection": {
    "requireResidentKey": true,
    "residentKey": "required",
    "userVerification": "discouraged"
  },
  "attestation": "direct"
}
Is there something here that is blocking the browser from detecting the yubikey?

**Comment by ynojima** [comment]
Since resident key is requested by `"requireResidentKey": true,` and `"residentKey": "required",` options, passkey is created and the new dialog is shown. If you switch it off, legacy dialog will be shown.

**Comment by billlyd123** [comment]
That makes sense. It should be able to recognize the tu ike y with the new user interface though right? Is there a better place to open a ticket for that?

**Comment by ynojima** [comment]
You should file a bug in the Chromium bugzilla: https://bugs.chromium.org/p/chromium/issues/list?q=component:Blink%3EWebAuthentication

**Comment by billlyd123** [comment]
thanks!
