### ISSUE TITLE
Relying party and passkeys

### ISSUE THREAD

**Issue by deepu105** [webauthn4j/webauthn4j#831]
From the documentation it si not very clear if the libarary is suitable for implementing a Relying Party (like https://github.com/Yubico/java-webauthn-server). I'm assuming its possible since Keycloak is using it. I'm also assuming since the library is FIDO2 compliant it should work for multi-device passkeys as well?

Would be nice to clarify these in docs

**Comment by ynojima** [comment]
Yes, WebAuthn4J can be used to impelemnt a Relying Party, and WebAuthn4J supports multi-device passkeys.

> Would be nice to clarify these in docs

Thank you for suggestion. I'd like to add a section regarding passkeys, when the time allows.

**Comment by deepu105** [comment]
Btw I created a simple passkeys demo using WebAuthn4j, which i'll be presenting at JFall netherlands as part of a passkeys talk

https://github.com/deepu105/webauthn4j-spring-boot-passkeys-demo

**Comment by ynojima** [comment]
Thank you for creating the demo!
Please share your slide and video after your session if possible.

**Comment by ynojima** [comment]
Addressed with https://github.com/webauthn4j/webauthn4j/pull/1044

**Comment by deepu105** [comment]
Here is the [video](https://www.youtube.com/watch?v=7R81uwxv1k0) from on eof the sessions and [slides](https://speakerdeck.com/deepu105/a-passwordless-future-passkeys-for-spring-developers)

**Comment by ynojima** [comment]
Wow, it was you! I saw the video. Thank you again for introducing WebAuthn4J!
