### ISSUE TITLE
Serialization and deserialization documentation correct for attestationStatement?

### ISSUE THREAD

**Issue by matsudamper** [webauthn4j/webauthn4j#864]
Is the documentation of the attestationStatement intentional?

`AttestationStatementEnvelope` has one argument, but two arguments are passed.  
`writeValueAsBytes` requires one argument but is not passed.
https://github.com/webauthn4j/webauthn4j/blob/7ec4f4f20221130aadce2cc01eb4182b88ecdd04/docs/src/reference/asciidoc/en/deep-dive.adoc?plain=1#L42-L43
https://github.com/webauthn4j/webauthn4j/blob/7ec4f4f20221130aadce2cc01eb4182b88ecdd04/docs/src/reference/asciidoc/en/deep-dive.adoc?plain=1#L59

Not really related to the above, but for the sake of simplicity, I thought it would be better without `static`.
https://github.com/webauthn4j/webauthn4j/blob/7ec4f4f20221130aadce2cc01eb4182b88ecdd04/docs/src/reference/asciidoc/en/deep-dive.adoc?plain=1#L48

**Comment by ynojima** [comment]
Thank you for pointing out! Fixed in https://github.com/webauthn4j/webauthn4j/pull/867
