### ISSUE TITLE
Update gradle to 5.x

### ISSUE THREAD

**Issue by ynojima** [webauthn4j/webauthn4j#9]
This issue blocks https://github.com/webauthn4j/webauthn4j/issues/8

gradle-bintray-plugin 1.7.3 doesn't work with gradle 5.x

**Comment by DavidAdamczyk** [comment]
Could i have more information how to reproduce this issue ? I currently have passed all test on JDK 11.0.2 and Gradle 5.2.1

**Comment by ynojima** [comment]
Thank you for your pull request! 
Although building and testing jar completes normally, Bintray plugin encounters an error when releasing an artifact.
Error log:
https://travis-ci.org/webauthn4j/webauthn4j/jobs/490110017#L760

Since the release is maintainer's task, I will fix it myself. Thanks!

**Comment by ynojima** [comment]
Fixed by https://github.com/webauthn4j/webauthn4j/commit/5973e29f352ee60c132e8270eff92ccb1426d15c
