### ISSUE TITLE
Document WebAuthnRegistrationManager and WebAuthnAuthenticationManager

### ISSUE THREAD

**Issue by adrianp-sti** [webauthn4j/webauthn4j#908]
In the documentation it might be worth just adding a note on WebAuthnManager and that it's also split into WebAuthnRegistrationManager and WebAuthnAuthenticationManager.  I didn't realise this and it was only after looking at some old pull requests I found it (https://github.com/webauthn4j/webauthn4j/pull/289).

**Comment by ynojima** [comment]
Thank you for suggestion. I'd like to add a note when the time allows.
