### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by laoziyaoshangtian** [webauthn4j/webauthn4j#926]
Where does the attestationObject data come from?

**Comment by laoziyaoshangtian** [comment]
Where does the attestationObject data come from?

**Comment by ynojima** [comment]
`attestationOjbect` is a field of [AuthenticatorAttestationResponse](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#authenticatorattestationresponse), which is returned from WebAuthn JS API.

If you have a question, please use Discussions board instead of filing a issue. Closing.

**Comment by laoziyaoshangtian** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
