### ISSUE TITLE
With what Java version is this library compatible

### ISSUE THREAD

**Issue by fungastorba** [webauthn4j/webauthn4j#952]
Sorry for asking a probably stupid question, 

but here [https://webauthn4j.github.io/webauthn4j/en/#language-framework](url) it says Java 8 or later.

Here [https://github.com/webauthn4j/webauthn4j?tab=readme-ov-file#prerequisites](url) it states: " To use WebAuthn4J library, JDK11 is OK"

So my question is can I use it with JDK 8?

**Comment by ynojima** [comment]
Sorry, from [0.22.0.RELEASE](https://github.com/webauthn4j/webauthn4j/releases/tag/0.22.0.RELEASE), JDK8 support is dropped.
I will update the reference document.
