### ISSUE TITLE
Release 0.25.1 is not in Maven Central

### ISSUE THREAD

**Issue by rwinch** [webauthn4j/webauthn4j#954]
It looks like webauthn4j 0.25.1 was [released](https://github.com/webauthn4j/webauthn4j/releases/tag/0.25.1.RELEASE), but I don't see it in Maven Central https://repo1.maven.org/maven2/com/webauthn4j/webauthn4j-core/0.25.1.RELEASE/

**Comment by ynojima** [comment]
Thanks for pointing that out. I've corrected it.
