### ISSUE TITLE
Add support for PublicKeyCredentialRequestOptions.attestation

### ISSUE THREAD

**Issue by rwinch** [webauthn4j/webauthn4j#982]
Add support for [PublicKeyCredentialRequestOptions.attestation](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialrequestoptions-attestation)

**Comment by ynojima** [comment]
`PublicKeyCredentialRequestOptions.attestationFormats` has already been removed from [the latest Working Draft](https://w3c.github.io/webauthn/#dictionary-assertion-options) by [this change](https://github.com/w3c/webauthn/pull/1997).
