### ISSUE TITLE
Add support for PublicKeyCredentialRequestOptions.attestationFormats

### ISSUE THREAD

**Issue by rwinch** [webauthn4j/webauthn4j#983]
Add support for [PublicKeyCredentialRequestOptions.attestationFormats](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialrequestoptions-attestationformats)

**Comment by ynojima** [comment]
`PublicKeyCredentialRequestOptions.attestationFormats` has already been removed from [the latest Working Draft](https://w3c.github.io/webauthn/#dictionary-assertion-options) by [this change](https://github.com/w3c/webauthn/pull/1997).
